title = "vLuau"

gitSourceBranch = "main"
changelog = true
classOrder = [
    "Main"
]
code = "src/vLuau.luau"

[docusaurus]
url = "https://littlebitsman.dev"
baseUrl = "/vLuau"
onBrokenLinks = "throw"
onBrokenMarkdownLinks = "throw"

[footer]
style = "dark"
copyright = "Copyright © 2025 littleBitsman. Docs built with Moonwave and Docusaurus"
